client:
  acks: 1
  retries: 1
  batch_size: 128
  linger_ms: 1
  # enable_idempotence: False
  partitioner: piz_component.kafka.support.RandomPartitioner
config:
  mode: ASYNC
  transactionProcessor:
    classpath: piz_component.kafka.producer.plugin.TransactionProcessor
  senderProcessor: 