client:
  acks: "all"
  buffer_memory: 33554432
  retries: 3
  batch_size: 16384
  linger_ms: 0
  request_timeout_ms: 30000
  send_buffer_bytes: 131072
  enable_idempotence: true
  max_in_flight_requests_per_connection: 5
  transaction_timeout_ms: 60000
  partitioner_class: org_pizazz_kafka_support_RandomPartitioner
config:
  mode: ASYNC_TRANSACTION
  transactionProcessor:
    classpath: org_pizazz_kafka_producer_TransactionProcessor
  senderProcessor: 