client:
  acks: 0
  buffer_memory: 67108864
  compression_type: none
  retries: 0
  batch_size: 32768
  linger_ms: 0
  max_request_size: 1028576
  request_timeout_ms: 30000
  # enable_idempotence: False
  max_in_flight_requests_per_connection: 15
  partitioner: piz_component.kafka.core.RandomPartitioner
config:
  mode: ASYNC
  transaction-processor:
    classpath: piz_component.kafka.producer.plugin.TransactionProcessor
  sender-processor: